OrdresAchat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('achat.urls')),
]

achat/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.order_form, name='home'),
    path('login/', views.user_login, name='login'),
    path('order_form/', views.order_form, name='order_form'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('get_article_field/', views.get_article_field, name='get_article_field'),
    path('get_filtered_formats_articles/', views.get_filtered_formats_articles, name='get_filtered_formats_articles'),
    path('get_filtered_articles/', views.get_filtered_articles, name='get_filtered_articles'),
    path('process_order_form/', views.process_order_form, name='process_order_form'),
]

achat/models.py
from django.db import models
from django.contrib.auth.models import User

class Fournisseur(models.Model):
    nom = models.CharField(max_length=255)
    
    def __str__(self):
        return self.nom

class Format(models.Model):
    nom = models.CharField(max_length=255)
    fournisseurs = models.ManyToManyField(Fournisseur)

    def article_count(self):
        return self.article_set.count()
    
    def __str__(self):
        return self.nom

class Article(models.Model):
    code = models.IntegerField()
    fournisseur = models.ForeignKey(Fournisseur, on_delete=models.CASCADE)
    format = models.ForeignKey(Format, on_delete=models.CASCADE)
    intitule = models.CharField(max_length=255)
    colisage_achat = models.CharField(max_length=255, default='', blank=True)
    port_embarquement = models.CharField(max_length=255, default='', blank=True)
    ean_carton = models.CharField(max_length=255, default='', blank=True)
    nomenclature = models.CharField(max_length=255, default='', blank=True)
    ean13 = models.CharField(max_length=255, default='', blank=True)
    origine_fournisseur = models.CharField(max_length=255, default='', blank=True)
    
    def __str__(self):
        return self.intitule

class Commande(models.Model):
    numero_ordre = models.IntegerField()
    utilisateur = models.ForeignKey(User, on_delete=models.CASCADE)
    code_article = models.CharField(max_length=255, default='')
    nom_fournisseur = models.CharField(max_length=255, default='')
    format = models.CharField(max_length=255, default='', blank=True)
    article = models.CharField(max_length=255, default='', blank=True)
    quantite = models.IntegerField()
    prix_achat_net = models.DecimalField(max_digits=10, decimal_places=2)
    colisage_achat = models.CharField(max_length=255)
    date_commande_origine = models.DateField()
    incoterm = models.CharField(max_length=255)
    taux_devise = models.DecimalField(max_digits=10, decimal_places=2)
    prix_devise = models.DecimalField(max_digits=10, decimal_places=2)
    port_embarquement = models.CharField(max_length=255)
    ean_carton = models.CharField(max_length=255)
    nomenclature = models.CharField(max_length=255)
    ean13 = models.CharField(max_length=255)
    etat_ordre = models.CharField(max_length=255, choices=[("prod", "prod"), ("confirme", "confirme"), ("annule", "annule")])
    origine_fournisseur = models.CharField(max_length=255)

    def __str__(self):
        return (
            f"Numero d'ordre: {self.numero_ordre}\n"
            f"Utilisateur: {self.utilisateur}\n"
            f"Code Article: {self.code_article}\n"
            f"Nom fournisseur: {self.nom_fournisseur}\n"
            f"Format: {self.format}\n"
            f"Article: {self.article}\n"
            f"Quantite: {self.quantite}\n"
            f"Prix Achat Net: {self.prix_achat_net}\n"
            f"Colisage Achat: {self.colisage_achat}\n"
            f"Date Commande Origine: {self.date_commande_origine}\n"
            f"Incoterm: {self.incoterm}\n"
            f"Taux Devise: {self.taux_devise}\n"
            f"Prix Devise: {self.prix_devise}\n"
            f"Port Embarquement: {self.port_embarquement}\n"
            f"EAN Carton: {self.ean_carton}\n"
            f"Nomenclature: {self.nomenclature}\n"
            f"EAN13: {self.ean13}\n"
            f"Etat Ordre: {self.etat_ordre}\n"
            f"Origine Fournisseur: {self.origine_fournisseur}\n"
        )

achat/forms.py
from django import forms
from .models import Fournisseur, Article, Format


class OrderForm(forms.Form):
    code_article = forms.CharField(
        label="Code Article:",
        widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'}),
        required=False,
    )
    nom_fournisseur = forms.ModelChoiceField(
        queryset=Fournisseur.objects.all(),
        empty_label="-- sélectionnez un fournisseur --",
        label="Nom Fournisseur:",
        required=False,
        widget=forms.Select(attrs={'class': 'form-control'}),
    )
    format = forms.ModelChoiceField(
        queryset=Format.objects.all(),
        empty_label="-- sélectionnez un format --",
        label="Format",
        required=False,
    )
    article = forms.ModelChoiceField(
        queryset=Article.objects.all(),
        empty_label="-- sélectionnez un article --",
        label="Article:",
        required=False,
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    quantite = forms.IntegerField(
        label="Quantité:",
        widget=forms.NumberInput(attrs={'class': 'form-control'})
    )
    prix_achat_net = forms.DecimalField(
        label="Prix d'achat net:",
        widget=forms.NumberInput(attrs={'class': 'form-control'})
    )
    colisage_achat = forms.CharField(
        label="Colisage achat:",
        widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'})
    )
    date_commande_origine = forms.DateField(
        label="Date commande origine:",
        input_formats=['%d/%m/%Y'],
        widget=forms.DateInput(attrs={'class': 'form-control'}),
    )
    incoterm = forms.CharField(
        label="Incoterm:",
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    taux_devise = forms.CharField(widget=forms.TextInput())
    prix_devise = forms.DecimalField(
        label="Prix en devise:",
        widget=forms.NumberInput(attrs={'class': 'form-control'})
    )
    port_embarquement = forms.CharField(
        label="Port d'embarquement:",
        widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'})
    )
    ean_carton = forms.CharField(
        label="EAN carton:",
        widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'})
    )
    nomenclature = forms.CharField(
        label="Nomenclature:",
        widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'})
    )
    ean13 = forms.CharField(
        label="EAN13:",
        widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'})
    )
    etat_ordre = forms.CharField(
        label="Etat de l'ordre:",
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    origine_fournisseur = forms.CharField(
        label="Origine fournisseur:",
        widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'})
    )

achat/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth import logout
from django.shortcuts import redirect
from .models import Fournisseur, Commande, Article, Format
from .forms import OrderForm
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
import json
from django.http import QueryDict
from time import time

def user_login(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect("/order_form/")
        else:
            return HttpResponse("Identifiants invalides.")
    return render(request, "achat/login.html")

@csrf_exempt
@login_required
def process_order_form(request):
    if request.method == "POST":
        # Convert JSON to QueryDict
        json_data = json.loads(request.body.decode("utf-8"))
        # print("json_data:", json_data)

        # Initialize a list to store the individual form data dicts
        data_list = []

        if isinstance(json_data, list):  # Check if json_data is a list
            for form_data in json_data:
                form_data_dict = QueryDict('', mutable=True)
                
                # Deserialize form_data if it's a string
                if isinstance(form_data, str):
                    form_data = json.loads(form_data)
                    
                # Iterate over the form_data dictionary and update form_data_dict
                for key, value in form_data.items():
                    form_data_dict[key] = value

                data_list.append(form_data_dict)
        else:  # If json_data is a single JSON object
            form_data_dict = QueryDict('', mutable=True)
            
            # Iterate over the json_data dictionary and update form_data_dict
            for key, value in json_data.items():
                form_data_dict[key] = value

            data_list.append(form_data_dict)

        # Initialize a list to store the Commande objects
        commandes = []

        # Initialize a variable to store any errors
        errors = {}

        # Iterate over the received form data
        for data in data_list:
            # Create a new instance of the form with the received data
            form = OrderForm(data)

            # Check if the form is valid
            if form.is_valid():
                
                format_to_insert = ""
                article_to_insert = ""
                formatObj = form.cleaned_data['format']
                articleObj = form.cleaned_data['article']
                if form.cleaned_data['format'] is not None and formatObj:
                    format_to_insert = formatObj.nom
                if form.cleaned_data['article'] is not None and articleObj:
                    article_to_insert = articleObj.intitule

                # Create a new Commande object with the form data
                commande = Commande(
                    utilisateur=request.user,
                    code_article=form.cleaned_data['code_article'],
                    nom_fournisseur=form.cleaned_data['nom_fournisseur'].nom,
                    format=format_to_insert,
                    article=article_to_insert,
                    quantite=form.cleaned_data['quantite'],
                    prix_achat_net=form.cleaned_data['prix_achat_net'],
                    colisage_achat=form.cleaned_data['colisage_achat'],
                    date_commande_origine=form.cleaned_data['date_commande_origine'],
                    incoterm=form.cleaned_data['incoterm'],
                    taux_devise=form.cleaned_data['taux_devise'],
                    prix_devise=form.cleaned_data['prix_devise'],
                    port_embarquement=form.cleaned_data['port_embarquement'],
                    ean_carton=form.cleaned_data['ean_carton'],
                    nomenclature=form.cleaned_data['nomenclature'],
                    ean13=form.cleaned_data['ean13'],
                    etat_ordre=form.cleaned_data['etat_ordre'],
                    origine_fournisseur=form.cleaned_data['origine_fournisseur']
                )

                # Add the Commande object to the list
                commandes.append(commande)
            else:
                # Add the current form's errors to the total errors
                errors.update(form.errors.get_json_data())

        # Check if there are any errors
        if errors:
            # Send a JSON response to the client with the error
            return JsonResponse({"errors": errors}, status=400)
        else:
            # Generate a unique numero_ordre using the current timestamp
            numero_ordre = int(time())

            # Save all the Commande objects in the database
            for commande in commandes:
                commande.numero_ordre = numero_ordre

                print(commande)
                print("---------------------------------------------")
                commande.save()

            # Send a JSON response to the client
            response_data = {
                "status": "success",
                "message": "Form data submitted successfully.",
            }
            return JsonResponse(response_data)
    return render(request, "achat/order_form.html", {'form': OrderForm()})

@login_required
def order_form(request):
    if request.method == 'GET':
        form = OrderForm()
        return render(request, "achat/order_form.html", {'form': form})

@login_required
def user_logout(request):
    logout(request)
    return redirect("login")

def autocomplete_code_articles(request):
    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        query = request.GET.get('term', '')
        form = OrderForm()
        form.fields['code_article'].queryset = Article.objects.filter(
            code__icontains=query)
        results = []
        for code_article in form.fields['code_article'].queryset:
            code_article_json = {}
            code_article_json['label'] = code_article.code
            code_article_json['value'] = code_article.pk
            results.append(code_article_json)
        return JsonResponse(results, safe=False)
    return HttpResponse("Requête non valide.")

def get_filtered_formats_articles(request):
    fournisseur_id = request.GET.get('fournisseur_id')
    fournisseur = Fournisseur.objects.get(id=fournisseur_id)

    # Use the reverse relationship between Fournisseur and Format
    formats = fournisseur.format_set.all()

    # Create a list of format dictionaries including the article count
    format_dicts = []
    articles = Article.objects.none()

    for format in formats:
        # Filter articles for the current fournisseur and format
        articles_for_format = Article.objects.filter(fournisseur=fournisseur, format=format)

        # Add the format to the format_dicts list if there are articles for it
        if articles_for_format.exists():
            format_dicts.append({"pk": format.pk, "nom": format.nom, "article_count": articles_for_format.count()})

            # If it's the first format, use its articles for the response
            if not articles:
                articles = articles_for_format

    data = {
        'formats': json.dumps(format_dicts),
        'articles': serializers.serialize('json', articles)
    }
    return JsonResponse(data)

def get_filtered_articles(request):
    fournisseur_id = request.GET.get('fournisseur_id')
    format_id = request.GET.get('format_id')
    articles = Article.objects.filter(
        fournisseur__id=fournisseur_id, format__id=format_id)
    data = {
        'articles': serializers.serialize('json', articles)
    }
    return JsonResponse(data)

def get_article_field(request):
    article_id = request.GET.get('article_id', None)

    if article_id is not None:
        try:
            article = Article.objects.get(pk=article_id)
            article_data = {
                'code': article.code,
                'colisage_achat': article.colisage_achat,
                'port_embarquement': article.port_embarquement,
                'ean_carton': article.ean_carton,
                'nomenclature': article.nomenclature,
                'ean13': article.ean13,
                'origine_fournisseur': article.origine_fournisseur,
            }
            return JsonResponse(article_data)
        except Article.DoesNotExist:
            return JsonResponse({"error": "Article not found."}, status=404)
    else:
        return JsonResponse({"error": "Article ID missing."}, status=400)

achat/templates/achat/base.html
<!DOCTYPE html>
<html lang="it">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Ordres Achat{% endblock %}</title>

    <!-- Include your CSS files here -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- Include Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <!-- Include Bootstrap 5 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css">

    <!-- Include Bootstrap 5 JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.bundle.min.js"></script>

    <!-- Include jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- Include JavaScript file -->
    <script src="{% static 'js/script.js' %}"></script>

    <!-- Include jQuery UI -->
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>


    <!-- Include datepicker CSS -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">

    <!-- Include datepicker -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light border">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
              {% if request.resolver_match.url_name != 'login' %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'order_form' %}">Commande</a>
              </li>
              {% if user.is_not_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Connexion</a>
              </li>
              {% endif %}
              {% endif %}
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link btn btn-danger" href="{% url 'logout' %}?next=/">Déconnexion</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </nav>
    </header>      
    <main>
        {% block content %}
        <!-- The content of other pages will be inserted here -->
        {% endblock %}
    </main>
    <footer>
        <!-- Footer here -->
    </footer>
</body>
</html>

achat/templates/achat/login.html
{% extends 'achat/base.html' %} {% block content %}

<div class="login-container">
  <h2>Connexion</h2>
  {% if error_message %}
  <p class="error-message">{{ error_message }}</p>
  {% endif %}
  <form method="post">
    {% csrf_token %}
    <div class="input-container">
      <label for="username">Nom d'utilisateur:</label>
      <input type="text" name="username" id="username" />
    </div>
    <div class="input-container">
      <label for="password">Mot de passe:</label>
      <input type="password" name="password" id="password" />
    </div>
    <div class="button-container">
      <input type="submit" value="Connexion" />
    </div>
  </form>
  <br>
  <hr>
  <div class="admin-link-container">
    <p> <a href="{% url 'admin:index' %}">Accès admin</a></p>
  </div>
</div>
{% endblock %}

achat/templates/achat/order_form.html
{% extends 'achat/base.html' %}

{% load widget_tweaks %}

{% block content %}

<div class="form-container">
  
  <form method="post" id="order-form">
    <div class="forms-container">
      <div id="form-fields-container">
        <div class="form-card">
          <fieldset class="input-group">
            {% csrf_token %}
            <legend>Formulaire commande</legend>
            <hr>

            <div class="form-group">
              <label for="nom_fournisseur">{{ form.nom_fournisseur.label }}</label>
              {{ form.nom_fournisseur|add_class:'form-control form-select'|attr:"id:nom_fournisseur" }}
            </div>

            <div class="form-group">
              <label for="format">{{ form.format.label }}</label>
              {{ form.format|add_class:'form-control form-select'|attr:"id:format" }}
            </div>

            <div class="form-group">
              <label for="id_article">{{ form.article.label }}</label>
              {{ form.article|add_class:'form-control form-select'|attr:"id:id_article" }}
            </div>

            <div class="form-group">
              <label for="code_article">{{ form.code_article.label }}</label>
              {{ form.colisage_achat|add_class:'form-control'|attr:"id:code_article" }}
            </div>
            
            <div class="form-group">
                <label for="quantite">{{ form.quantite.label }}</label>
                {{ form.quantite|add_class:'form-control'|attr:"id:quantite" }}
            </div>
            
            <div class="form-group">
                <label for="prix_achat_net">{{ form.prix_achat_net.label }}</label>
                {{ form.prix_achat_net|add_class:'form-control'|attr:"id:prix_achat_net" }}
            </div>
            
            <div class="form-group">
                <label for="colisage_achat">{{ form.colisage_achat.label }}</label>
                {{ form.colisage_achat|add_class:'form-control'|attr:"id:colisage_achat" }}
            </div>
              
            <div class="form-group">
                <label for="{{ form.date_commande_origine.id_for_label }}">{{ form.date_commande_origine.label }}</label>
                {{ form.date_commande_origine|add_class:'form-control'|attr:"id:id_date_commande_origine" }}
            </div>
            
            <div class="form-group">
                <label for="{{ form.incoterm.id_for_label }}">{{ form.incoterm.label }}</label>
                {{ form.incoterm|add_class:'form-control'|attr:"id:id_incoterm" }}
            </div>
            
            <div class="form-group">
                <label for="{{ form.taux_devise.id_for_label }}">{{ form.taux_devise.label }}</label>
                {{ form.taux_devise|add_class:'form-control'|attr:"id:id_taux_devise" }}
            </div>
            
            <div class="form-group">
                <label for="{{ form.prix_devise.id_for_label }}">{{ form.prix_devise.label }}</label>
                {{ form.prix_devise|add_class:'form-control'|attr:"id:id_prix_devise" }}
            </div>
            
            <div class="form-group">
                <label for="{{ form.port_embarquement.id_for_label }}">{{ form.port_embarquement.label }}</label>
                {{ form.port_embarquement|add_class:'form-control'|attr:"id:port_embarquement" }}
            </div>
            
            <div class="form-group">
                <label for="{{ form.ean_carton.id_for_label }}">{{ form.ean_carton.label }}</label>
                {{ form.ean_carton|add_class:'form-control'|attr:"id:ean_carton" }}
            </div>
            
            <div class="form-group">
                <label for="{{ form.nomenclature.id_for_label }}">{{ form.nomenclature.label }}</label>
                {{ form.nomenclature|add_class:'form-control'|attr:"id:nomenclature" }}
            </div>
            
            <div class="form-group">
                <label for="{{ form.ean13.id_for_label }}">{{ form.ean13.label }}</label>
                {{ form.ean13|add_class:'form-control'|attr:"id:ean13" }}
            </div>
            
            <div class="form-group">
                <label for="{{ form.etat_ordre.id_for_label }}">{{ form.etat_ordre.label }}</label>
                {{ form.etat_ordre|add_class:'form-control'|attr:"id:id_etat_ordre" }}
            </div>
            
            <div class="form-group">
                <label for="{{ form.origine_fournisseur.id_for_label }}">{{ form.origine_fournisseur.label }}</label>
                {{ form.origine_fournisseur|add_class:'form-control'|attr:"id:origine_fournisseur" }}
            </div>

          </fieldset>
        </div>
      </div>
    </div>
    <div class="form-card card-footer">
        <button type="button" id="add-form"><a><i class="fas fa-plus"></i></a></button>
    </div>
    <div class="button-container">
        <input type="submit" value="Enregistrer en base">
    </div>
    <div id="flash-message-container" class="d-none">
      <div class="flash-message-backdrop"></div>
      <div class="alert alert-success flash-message" role="alert">
        <span id="flash-message"></span>
      </div>
    </div>
    <br>
  </form>
</div>
{% endblock %}